POST http://localhost:4001/products
content-Type: application/json

{
  "name": "Caderno 96 folhas",
  "price": 16.87
}

###
GET http://localhost:4001/products

###
GET http://localhost:4001/products/

###
PUT http://localhost:4001/products/
content-Type: application/json

{
  "name": "Caneta Lilás",
  "price": 3.75
}

###
DELETE http://localhost:4001/products/